version: "3"
services:
  evisa:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: evisa
    volumes:
      - ./:/usr/src/evisa
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
