apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: evisa-ing
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: evisa-vn-tls
      hosts:
        - evisa-vn.com
  rules:
    - host: evisa-vn.com
      http:
        paths:
        - path: /
          backend:
            serviceName: evisa
            servicePort: 80